#!/bin/bash

source ./etc/conf
source ./repos/epel

case $1 in
  --install)
      if [ "${IF_TRUE}" != "true" ]
      then
          epel_install
          ${YUM_INSTALL} ansible >> "${LOG}" 2>&1
          echo -e "\nAnsible instalado com sucesso\n"
          exit 0
      else
          echo -e "\nAnsible já está instalado\n"
          exit 0
      fi
      ;;
  --remove)
      if [ "${IF_TRUE}" == "true" ]
      then
          ${YUM_REMOVE} ansible >> "${LOG}" 2>&1
          echo -e "\nAnsible removido com sucesso\n"
          exit 0
      else
          echo -e "\nAnsible não está instalado\n"
      fi
      ;;
  *)
      echo -e "\nUtilize [--install | --remove]\n"
      ;;
esac